import {
  AlignmentType,
  BorderStyle,
  Document,
  Footer,
  Header,
  PageNumber,
  PageOrientation,
  Packer,
  Paragraph,
  ShadingType,
  Table,
  TableBorders,
  TableCell,
  TableLayoutType,
  TableRow,
  TextRun,
  WidthType,
  type ISectionOptions,
} from 'docx'
import { withoutHash } from '../branding'
import type {
  DocumentReport,
  ReportBlock,
  ReportColumns,
  ReportList,
  ReportParagraph,
  ReportSection,
  ReportTable,
  ReportTableCell,
} from '../types'

type DocxBlock = Paragraph | Table

export async function renderDocx(report: DocumentReport): Promise<Uint8Array> {
  const primary = withoutHash(report.branding.primaryColor)
  const section: ISectionOptions = {
    properties: {
      page: {
        // docx swaps width and height itself for landscape orientation. Always supply Letter's
        // portrait dimensions here or Word receives a landscape flag with portrait proportions.
        size: {
          width: 12240,
          height: 15840,
          orientation:
            report.orientation === 'landscape'
              ? PageOrientation.LANDSCAPE
              : PageOrientation.PORTRAIT,
        },
        margin: { top: 1080, right: 1080, bottom: 1080, left: 1080, header: 420, footer: 420 },
      },
    },
    ...(report.showHeaderFooter === false
      ? {}
      : {
          headers: {
            default: new Header({
              children: [
                new Paragraph({
                  border: { bottom: { style: BorderStyle.SINGLE, size: 5, color: primary } },
                  spacing: { after: 120 },
                  children: [
                    new TextRun({
                      text: report.branding.churchName,
                      bold: true,
                      color: primary,
                      size: 18,
                    }),
                  ],
                }),
              ],
            }),
          },
          footers: {
            default: new Footer({
              children: [
                new Paragraph({
                  alignment: AlignmentType.CENTER,
                  children: [
                    new TextRun({
                      text: 'Generated by Worship Studio  ·  ',
                      color: '777777',
                      size: 16,
                    }),
                    new TextRun({ children: [PageNumber.CURRENT], color: '777777', size: 16 }),
                  ],
                }),
              ],
            }),
          },
        }),
    children: [
      ...(report.showTitle === false
        ? []
        : [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              spacing: { after: 80 },
              children: [
                new TextRun({ text: report.title, bold: true, size: 32, color: '202833' }),
              ],
            }),
          ]),
      ...(report.showTitle !== false && report.subtitle
        ? [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              spacing: { after: 320 },
              children: [new TextRun({ text: report.subtitle, color: '666666', size: 19 })],
            }),
          ]
        : []),
      ...report.blocks.flatMap((block) => renderBlock(block, primary)),
    ],
  }

  const document = new Document({
    creator: 'Worship Studio',
    title: report.title,
    subject: report.subject,
    description: report.subtitle,
    sections: [section],
  })
  const blob = await Packer.toBlob(document)
  return new Uint8Array(await blob.arrayBuffer())
}

function renderBlock(block: ReportBlock, primary: string): DocxBlock[] {
  switch (block.kind) {
    case 'paragraph':
      return [renderParagraph(block)]
    case 'table':
      return [renderTable(block, primary)]
    case 'list':
      return renderList(block, primary)
    case 'columns':
      return [renderColumns(block, primary)]
    case 'section':
      return renderSection(block, primary)
  }
}

function renderParagraph(block: ReportParagraph): Paragraph {
  const size =
    block.style === 'title'
      ? 32
      : block.style === 'heading'
        ? 23
        : block.style === 'subtitle'
          ? 19
          : block.style === 'note'
            ? 18
            : 20
  const color =
    block.style === 'note' || block.style === 'subtitle'
      ? '777777'
      : block.style === 'title'
        ? '202833'
        : undefined
  return new Paragraph({
    alignment: alignment(block.alignment),
    spacing: {
      before: pointsToTwips(block.spacingBefore ?? 0),
      after: pointsToTwips(block.spacingAfter ?? (block.style === 'body' ? 2 : 5)),
    },
    children: block.runs.map(
      (run) =>
        new TextRun({
          text: run.text,
          bold: run.bold,
          italics: run.italics ?? block.style === 'note',
          color: run.color ? withoutHash(run.color) : color,
          size,
        }),
    ),
  })
}

function renderTable(block: ReportTable, primary: string): Table {
  const header = block.headers.length
    ? [
        new TableRow({
          tableHeader: true,
          children: block.headers.map(
            (text) =>
              new TableCell({
                shading: { type: ShadingType.CLEAR, fill: primary, color: 'auto' },
                children: [
                  new Paragraph({
                    children: [new TextRun({ text, bold: true, color: 'FFFFFF', size: 17 })],
                  }),
                ],
              }),
          ),
        }),
      ]
    : []
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      ...header,
      ...block.rows.map(
        (row) =>
          new TableRow({
            children: row.map((cell) => renderTableCell(cell)),
          }),
      ),
    ],
  })
}

function renderTableCell(cell: ReportTableCell): TableCell {
  return new TableCell({
    children: [
      new Paragraph({
        alignment: alignment(cell.alignment),
        spacing: { before: 55, after: 55 },
        children: cell.runs.map(
          (run) =>
            new TextRun({
              text: run.text,
              bold: run.bold,
              italics: run.italics,
              color: run.color ? withoutHash(run.color) : undefined,
              size: 18,
            }),
        ),
      }),
    ],
  })
}

function renderList(block: ReportList, primary: string): Paragraph[] {
  const heading = block.heading
    ? [
        new Paragraph({
          spacing: { after: 50 },
          children: [new TextRun({ text: block.heading, bold: true, color: primary, size: 18 })],
        }),
      ]
    : []
  const items = block.items.length ? block.items : [block.emptyText ?? 'None']
  return [
    ...heading,
    ...items.map(
      (item, index) =>
        new Paragraph({
          indent: { left: 180, hanging: 140 },
          spacing: { after: 30 },
          children: [
            new TextRun({
              text: `${block.items.length ? (block.ordered ? `${index + 1}.` : '•') : '—'} ${item}`,
              italics: block.items.length === 0,
              color: block.items.length === 0 ? '777777' : undefined,
              size: 18,
            }),
          ],
        }),
    ),
  ]
}

function renderColumns(block: ReportColumns, primary: string): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    // Word otherwise auto-fits around the populated left cell and collapses an intentionally
    // blank right bulletin panel instead of preserving the requested equal-width layout.
    layout: TableLayoutType.FIXED,
    borders: TableBorders.NONE,
    rows: [
      new TableRow({
        children: block.columns.map(
          (column) =>
            new TableCell({
              width:
                typeof column.width === 'number'
                  ? { size: column.width, type: WidthType.DXA }
                  : { size: Math.floor(100 / block.columns.length), type: WidthType.PERCENTAGE },
              margins: {
                right: pointsToTwips((block.gap ?? 12) / 2),
                left: pointsToTwips((block.gap ?? 12) / 2),
              },
              children: column.blocks.flatMap((child) => renderBlock(child, primary)),
            }),
        ),
      }),
    ],
  })
}

function renderSection(block: ReportSection, primary: string): DocxBlock[] {
  const accent = withoutHash(block.accent ?? `#${primary}`)
  return [
    new Paragraph({
      keepNext: true,
      spacing: { before: 240, after: 30 },
      border: { bottom: { style: BorderStyle.SINGLE, size: 5, color: accent } },
      children: [new TextRun({ text: block.heading, bold: true, color: accent, size: 23 })],
    }),
    ...(block.subheading
      ? [
          new Paragraph({
            keepNext: true,
            spacing: { after: 100 },
            children: [new TextRun({ text: block.subheading, color: '666666', size: 17 })],
          }),
        ]
      : []),
    ...block.blocks.flatMap((child) => renderBlock(child, primary)),
  ]
}

function alignment(
  value: 'left' | 'center' | 'right' | undefined,
): (typeof AlignmentType)[keyof typeof AlignmentType] {
  if (value === 'center') return AlignmentType.CENTER
  if (value === 'right') return AlignmentType.RIGHT
  return AlignmentType.LEFT
}

function pointsToTwips(points: number): number {
  return Math.round(points * 20)
}
