import {
  AlignmentType,
  BorderStyle,
  Document,
  Footer,
  Header,
  PageNumber,
  PageOrientation,
  Packer,
  Paragraph,
  ShadingType,
  Table,
  TableBorders,
  TableCell,
  TableLayoutType,
  TableRow,
  TextRun,
  WidthType,
  type IBordersOptions,
  type ISectionOptions,
} from 'docx'
import { withoutHash } from '../branding'
import type {
  DocumentReport,
  ReportBlock,
  ReportColumns,
  ReportList,
  ReportParagraph,
  ReportRun,
  ReportSection,
  ReportTable,
  ReportTableCell,
} from '../types'

type DocxBlock = Paragraph | Table

export async function renderDocx(report: DocumentReport): Promise<Uint8Array> {
  const primary = withoutHash(report.branding.primaryColor)
  const pageFooter = buildPageFooter(report, primary)
  const section: ISectionOptions = {
    properties: {
      page: {
        // docx swaps width and height itself for landscape orientation. Always supply Letter's
        // portrait dimensions here or Word receives a landscape flag with portrait proportions.
        size: {
          width: 12240,
          height: 15840,
          orientation:
            report.orientation === 'landscape'
              ? PageOrientation.LANDSCAPE
              : PageOrientation.PORTRAIT,
        },
        // The bulletin (showHeaderFooter: false) prints its own two-column layout at tight
        // margins (0.3in sides, 0.4in top/bottom) with its footer set further in (0.6in) for
        // clear separation from the content above it — every other report keeps the wider
        // default that leaves room for the branded header/footer.
        margin:
          report.showHeaderFooter === false
            ? { top: 576, right: 432, bottom: 576, left: 432, header: 420, footer: 864 }
            : { top: 1080, right: 1080, bottom: 1080, left: 1080, header: 420, footer: 420 },
      },
    },
    ...(report.showHeaderFooter === false
      ? {}
      : {
          headers: {
            default: new Header({
              children: [
                new Paragraph({
                  border: { bottom: { style: BorderStyle.SINGLE, size: 5, color: primary } },
                  spacing: { after: 120 },
                  children: [
                    new TextRun({
                      text: report.branding.churchName,
                      bold: true,
                      color: primary,
                      size: 18,
                    }),
                  ],
                }),
              ],
            }),
          },
        }),
    ...(pageFooter ? { footers: { default: pageFooter } } : {}),
    children: [
      ...(report.showTitle === false
        ? []
        : [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              spacing: { after: 80 },
              children: [
                new TextRun({ text: report.title, bold: true, size: 32, color: '202833' }),
              ],
            }),
          ]),
      ...(report.showTitle !== false && report.subtitle
        ? [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              spacing: { after: 320 },
              children: [new TextRun({ text: report.subtitle, color: '666666', size: 19 })],
            }),
          ]
        : []),
      ...report.blocks.flatMap((block) => renderBlock(block, primary)),
    ],
  }

  const document = new Document({
    creator: 'Worship Studio',
    title: report.title,
    subject: report.subject,
    description: report.subtitle,
    // Without an explicit default, Word falls back to its own generic template font — visibly
    // plainer than the PDF renderer's deliberately chosen (and embedded, so always-available)
    // Roboto. Word only *references* a font by name rather than embedding it, so this isn't as
    // guaranteed as the PDF's — but Roboto ships widely enough (Office itself, most browsers,
    // Google Fonts) that this is a close, reliable match in practice, and Word substitutes
    // gracefully rather than erroring on the rare machine that lacks it.
    styles: { default: { document: { run: { font: 'Roboto' } } } },
    sections: [section],
  })
  const blob = await Packer.toBlob(document)
  return new Uint8Array(await blob.arrayBuffer())
}

/** Word's own section Footer is genuinely pinned to the bottom of every page regardless of how
 *  much body content precedes it — the branded "Generated by..." footer for most reports, or (for
 *  the bulletin, which turns that off) `pageFooterColumns` laid out the same way the content
 *  columns above it are, so each footer lines up under its own page. Undefined when neither
 *  applies. */
function buildPageFooter(report: DocumentReport, primary: string): Footer | undefined {
  if (report.showHeaderFooter !== false) {
    return new Footer({
      children: [
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [
            new TextRun({ text: 'Generated by Worship Studio  ·  ', color: '777777', size: 16 }),
            new TextRun({ children: [PageNumber.CURRENT], color: '777777', size: 16 }),
          ],
        }),
      ],
    })
  }
  if (report.pageFooterColumns) {
    return new Footer({
      children: [
        renderColumns({ kind: 'columns', columns: report.pageFooterColumns, gap: 36 }, primary),
      ],
    })
  }
  return undefined
}

function renderBlock(block: ReportBlock, primary: string): DocxBlock[] {
  switch (block.kind) {
    case 'paragraph':
      return [renderParagraph(block)]
    case 'table':
      return [renderTable(block, primary)]
    case 'list':
      return renderList(block, primary)
    case 'columns':
      return [renderColumns(block, primary)]
    case 'section':
      return renderSection(block, primary)
  }
}

function renderParagraph(block: ReportParagraph): Paragraph {
  const size =
    block.style === 'title'
      ? 32
      : block.style === 'heading'
        ? 23
        : block.style === 'subtitle'
          ? 19
          : block.style === 'note'
            ? 18
            : 20
  const color =
    block.style === 'note' || block.style === 'subtitle'
      ? '777777'
      : block.style === 'title'
        ? '202833'
        : undefined
  return new Paragraph({
    alignment: alignment(block.alignment),
    spacing: {
      before: pointsToTwips(block.spacingBefore ?? 0),
      after: pointsToTwips(block.spacingAfter ?? (block.style === 'body' ? 2 : 5)),
    },
    children: block.runs.map(
      (run) =>
        new TextRun({
          text: run.text,
          bold: run.bold,
          italics: run.italics ?? block.style === 'note',
          underline: run.underline ? {} : undefined,
          color: run.color ? withoutHash(run.color) : color,
          size: run.fontSize ? pointsToHalfPoints(run.fontSize) : size,
        }),
    ),
  })
}

const NO_BORDER = { style: BorderStyle.NONE, size: 0, color: 'auto' } as const
// A thin gray rule under every row instead of a full grid — a modern, print-friendly look for
// content meant to sit on a monochrome page (the bulletin's serving schedule) rather than the
// boxed-in grid used elsewhere.
const ROW_DIVIDER = { style: BorderStyle.SINGLE, size: 4, color: '999999' } as const

function renderTable(block: ReportTable, primary: string): Table {
  const modern = !!block.plainHeader
  const cellBorders: IBordersOptions | undefined = modern
    ? { top: NO_BORDER, left: NO_BORDER, right: NO_BORDER, bottom: ROW_DIVIDER }
    : undefined
  const header = block.headers.length
    ? [
        new TableRow({
          tableHeader: true,
          children: block.headers.map(
            (text) =>
              new TableCell({
                shading: modern ? undefined : { type: ShadingType.CLEAR, fill: primary, color: 'auto' },
                borders: cellBorders,
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text,
                        bold: true,
                        color: modern ? '000000' : 'FFFFFF',
                        size: block.headerFontSize ? pointsToHalfPoints(block.headerFontSize) : 17,
                      }),
                    ],
                  }),
                ],
              }),
          ),
        }),
      ]
    : []
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: modern ? TableBorders.NONE : undefined,
    rows: [
      ...header,
      ...block.rows.map(
        (row) =>
          new TableRow({
            children: row.map((cell) => renderTableCell(cell, cellBorders)),
          }),
      ),
    ],
  })
}

function renderTableCell(cell: ReportTableCell, borders?: IBordersOptions): TableCell {
  const lines = [cell.runs, ...(cell.extraLines ?? [])]
  return new TableCell({
    borders,
    children: lines.map(
      (lineRuns, index) =>
        new Paragraph({
          alignment: alignment(cell.alignment),
          spacing: {
            before: index === 0 ? 55 : 0,
            after: index === lines.length - 1 ? 55 : 20,
          },
          children: lineRuns.map(
            (run) =>
              new TextRun({
                text: run.text,
                bold: run.bold,
                italics: run.italics,
                underline: run.underline ? {} : undefined,
                color: run.color ? withoutHash(run.color) : undefined,
                size: run.fontSize ? pointsToHalfPoints(run.fontSize) : 18,
              }),
          ),
        }),
    ),
  })
}

function renderList(block: ReportList, primary: string): Paragraph[] {
  const heading = block.heading
    ? [
        new Paragraph({
          spacing: { after: 50 },
          children: [
            new TextRun({
              text: block.heading,
              bold: true,
              color: block.headingColor ? withoutHash(block.headingColor) : primary,
              size: block.headingFontSize ? pointsToHalfPoints(block.headingFontSize) : 18,
            }),
          ],
        }),
      ]
    : []
  const items = block.items.length ? block.items : [block.emptyText ?? 'None']
  return [
    ...heading,
    ...items.map((item, index) => {
      const bullet = `${block.items.length ? (block.ordered ? `${index + 1}.` : '•') : '—'} `
      const runs: ReportRun[] =
        typeof item === 'string'
          ? [{ text: item, italics: block.items.length === 0, color: block.items.length === 0 ? '777777' : undefined }]
          : item
      return new Paragraph({
        indent: { left: 180, hanging: 140 },
        spacing: { after: 30 },
        children: [
          new TextRun({ text: bullet, size: 18 }),
          ...runs.map(
            (run) =>
              new TextRun({
                text: run.text,
                bold: run.bold,
                italics: run.italics,
                underline: run.underline ? {} : undefined,
                color: run.color ? withoutHash(run.color) : undefined,
                size: run.fontSize ? pointsToHalfPoints(run.fontSize) : 18,
              }),
          ),
        ],
      })
    }),
  ]
}

function renderColumns(block: ReportColumns, primary: string): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    // Word otherwise auto-fits around the populated left cell and collapses an intentionally
    // blank right bulletin panel instead of preserving the requested equal-width layout.
    layout: TableLayoutType.FIXED,
    borders: TableBorders.NONE,
    rows: [
      new TableRow({
        children: block.columns.map(
          (column) =>
            new TableCell({
              width:
                typeof column.width === 'number'
                  ? { size: column.width, type: WidthType.DXA }
                  : { size: Math.floor(100 / block.columns.length), type: WidthType.PERCENTAGE },
              // Word's own default cell margins otherwise add visible top/bottom padding around
              // this cell's content — invisible for a whole-page 2-column layout, but a real
              // (and confusing) gap for a single-line "role ... person" row, since that's the
              // *only* place this Table trick is used for something that isn't the full page.
              margins: {
                top: 0,
                bottom: 0,
                right: pointsToTwips((block.gap ?? 12) / 2),
                left: pointsToTwips((block.gap ?? 12) / 2),
              },
              children: column.blocks.flatMap((child) => renderBlock(child, primary)),
            }),
        ),
      }),
    ],
  })
}

function renderSection(block: ReportSection, primary: string): DocxBlock[] {
  const accent = withoutHash(block.accent ?? `#${primary}`)
  return [
    new Paragraph({
      keepNext: true,
      spacing: { before: 240, after: 30 },
      border: { bottom: { style: BorderStyle.SINGLE, size: 5, color: accent } },
      children: [new TextRun({ text: block.heading, bold: true, color: accent, size: 23 })],
    }),
    ...(block.subheading
      ? [
          new Paragraph({
            keepNext: true,
            spacing: { after: 100 },
            children: [new TextRun({ text: block.subheading, color: '666666', size: 17 })],
          }),
        ]
      : []),
    ...block.blocks.flatMap((child) => renderBlock(child, primary)),
  ]
}

function alignment(
  value: 'left' | 'center' | 'right' | undefined,
): (typeof AlignmentType)[keyof typeof AlignmentType] {
  if (value === 'center') return AlignmentType.CENTER
  if (value === 'right') return AlignmentType.RIGHT
  return AlignmentType.LEFT
}

function pointsToTwips(points: number): number {
  return Math.round(points * 20)
}

function pointsToHalfPoints(points: number): number {
  return Math.round(points * 2)
}
