import type { Content, TDocumentDefinitions } from 'pdfmake/interfaces'
import type {
  DocumentReport,
  ReportBlock,
  ReportColumns,
  ReportList,
  ReportParagraph,
  ReportRun,
  ReportSection,
  ReportTable,
  ReportTableCell,
} from '../types'

export async function renderPdf(report: DocumentReport): Promise<Uint8Array> {
  const [pdfMakeModule, vfsModule] = await Promise.all([
    import('pdfmake/build/pdfmake'),
    import('pdfmake/build/vfs_fonts'),
  ])
  const pdfMake = pdfMakeModule.default
  pdfMake.addVirtualFileSystem(vfsModule.default)

  const definition: TDocumentDefinitions = {
    info: {
      title: report.title,
      subject: report.subject,
      author: report.branding.churchName,
      creator: 'Worship Studio',
    },
    pageSize: 'LETTER',
    pageOrientation: report.orientation ?? 'portrait',
    // The bulletin (showHeaderFooter: false) prints its own two-column layout at tight margins
    // (0.3in sides, 0.4in top) — every other report keeps the wider default that leaves room for
    // the branded header/footer. The bottom margin is deliberately generous: it has to hold the
    // pinned footer (positioned 0.6in from the page edge, see buildPdfFooter) plus that footer's
    // own text height, not just the requested 0.4in body-content gap.
    pageMargins: report.showHeaderFooter === false ? [21.6, 28.8, 21.6, 92] : [54, 68, 54, 58],
    ...(report.showHeaderFooter === false
      ? {}
      : {
          header: {
            margin: [54, 24, 54, 0],
            columns: [
              {
                text: report.branding.churchName,
                color: report.branding.primaryColor,
                bold: true,
                fontSize: 9,
              },
              { text: report.title, alignment: 'right', color: '#777777', fontSize: 8 },
            ],
          },
        }),
    ...(buildPdfFooter(report) ? { footer: buildPdfFooter(report)! } : {}),
    content: [
      ...(report.showTitle === false
        ? []
        : [{ text: report.title, style: 'reportTitle' } as Content]),
      ...(report.showTitle !== false && report.subtitle
        ? [{ text: report.subtitle, style: 'reportSubtitle' } as Content]
        : []),
      ...report.blocks.map((block) => renderBlock(block, report.branding.primaryColor)),
    ],
    // Word never applies an artificial per-line multiplier like this (it uses the font's own
    // natural "single" spacing) — 1.2 was already generous for the other reports' smaller
    // default text, but on the bulletin's larger, explicit-fontSize text it compounds across
    // every line enough to spill a page that fits fine in Word onto a second one. Scoped to the
    // bulletin only so the other reports' existing typography doesn't shift.
    defaultStyle: {
      font: 'Roboto',
      fontSize: 9,
      color: '#252A31',
      lineHeight: report.showHeaderFooter === false ? 1.0 : 1.2,
    },
    styles: {
      reportTitle: {
        fontSize: 20,
        bold: true,
        alignment: 'center',
        color: '#202833',
        margin: [0, 0, 0, 4],
      },
      reportSubtitle: { fontSize: 9, alignment: 'center', color: '#666666', margin: [0, 0, 0, 20] },
      heading: { fontSize: 12, bold: true, color: '#202833' },
      note: { fontSize: 8, italics: true, color: '#777777' },
    },
  }

  const buffer = await pdfMake.createPdf(definition).getBuffer()
  return new Uint8Array(buffer)
}

/** pdfmake's `footer` callback is genuinely pinned to the bottom of every page regardless of how
 *  much body content precedes it — the branded "Generated by..."/page-number footer for most
 *  reports, or (for the bulletin, which turns that off) `pageFooterColumns` laid out the same
 *  way the content columns above it are, so each footer lines up under its own page. Undefined
 *  when neither applies. */
function buildPdfFooter(
  report: DocumentReport,
): ((currentPage: number, pageCount: number) => Content) | undefined {
  if (report.showHeaderFooter !== false) {
    return (currentPage: number, pageCount: number) => ({
      margin: [54, 0, 54, 18],
      columns: [
        { text: 'Generated by Worship Studio', color: '#888888', fontSize: 7 },
        {
          text: `${currentPage} / ${pageCount}`,
          alignment: 'right',
          color: '#888888',
          fontSize: 7,
        },
      ],
    })
  }
  if (report.pageFooterColumns) {
    const primary = report.branding.primaryColor
    return () => ({
      // 21.6pt (0.3in) sides to match the bulletin's own side margins; 18pt (0.25in) bottom
      // keeps the text off the physical page edge, well within the page's own 92pt reserved
      // bottom margin (see pageMargins above) sized for this footer.
      margin: [21.6, 0, 21.6, 18],
      columnGap: 36,
      columns: report.pageFooterColumns!.map((column) => ({
        width: column.width ?? '*',
        stack: column.blocks.map((child) => renderBlock(child, primary)),
      })),
    })
  }
  return undefined
}

function renderBlock(block: ReportBlock, primary: string): Content {
  switch (block.kind) {
    case 'paragraph':
      return renderParagraph(block)
    case 'table':
      return renderTable(block, primary)
    case 'list':
      return renderList(block, primary)
    case 'columns':
      return renderColumns(block, primary)
    case 'section':
      return renderSection(block, primary)
  }
}

function renderParagraph(block: ReportParagraph): Content {
  return {
    text: block.runs.map((run) => ({
      text: run.text,
      bold: run.bold,
      italics: run.italics,
      decoration: run.underline ? 'underline' : undefined,
      color: run.color,
      fontSize: run.fontSize,
    })),
    alignment: block.alignment,
    style:
      block.style === 'title'
        ? 'reportTitle'
        : block.style === 'subtitle'
          ? 'reportSubtitle'
          : block.style === 'heading'
            ? 'heading'
            : block.style === 'note'
              ? 'note'
              : undefined,
    margin: [
      0,
      block.spacingBefore ?? 0,
      0,
      block.spacingAfter ?? (block.style === 'body' ? 2 : 5),
    ],
  } as unknown as Content
}

function renderTableCellContent(cell: ReportTableCell) {
  const lines = [cell.runs, ...(cell.extraLines ?? [])]
  const renderLine = (runs: ReportRun[]) => ({
    text: runs.map((run) => ({
      text: run.text,
      bold: run.bold,
      italics: run.italics,
      decoration: run.underline ? 'underline' : undefined,
      color: run.color,
      fontSize: run.fontSize,
    })),
    margin: [0, 0, 0, 2],
  })
  return {
    // A single line renders as plain text (no wrapping stack needed); multiple lines (e.g. one
    // name per line) use a stack so each gets its own paragraph within the cell.
    ...(lines.length > 1 ? { stack: lines.map(renderLine) } : renderLine(cell.runs)),
    alignment: cell.alignment,
    margin: [2, 3, 2, 3],
    fontSize: 8,
  }
}

function renderTable(block: ReportTable, primary: string): Content {
  const modern = !!block.plainHeader
  const header = block.headers.map((text) => ({
    text,
    bold: true,
    color: modern ? '#000000' : '#FFFFFF',
    fillColor: modern ? undefined : primary,
    fontSize: block.headerFontSize ?? 8,
    margin: [2, 3, 2, 3],
  }))
  const rows = block.rows.map((row) => row.map(renderTableCellContent))
  return {
    table: {
      headerRows: block.headers.length ? (block.headerRows ?? 1) : 0,
      widths: block.widths ?? block.headers.map(() => '*'),
      body: block.headers.length ? [header, ...rows] : rows,
    },
    // A thin gray rule under every row instead of a full grid — a modern, print-friendly look
    // for content meant to sit on a monochrome page (the bulletin's serving schedule) rather
    // than the boxed-in grid used elsewhere.
    layout: modern
      ? {
          hLineColor: () => '#999999',
          vLineWidth: () => 0,
          hLineWidth: () => 0.75,
        }
      : {
          hLineColor: () => '#D9DDE3',
          vLineColor: () => '#D9DDE3',
          hLineWidth: () => 0.5,
          vLineWidth: () => 0.5,
        },
    margin: [0, 0, 0, 10],
  } as unknown as Content
}

function renderList(block: ReportList, primary: string): Content {
  const hasRealItems = block.items.length > 0
  const items = hasRealItems ? block.items : [block.emptyText ?? 'None']
  const renderItem = (item: string | ReportRun[]) => {
    if (typeof item === 'string') {
      return { text: item, color: hasRealItems ? undefined : '#777777', italics: !hasRealItems }
    }
    return {
      text: item.map((run) => ({
        text: run.text,
        bold: run.bold,
        italics: run.italics,
        decoration: run.underline ? 'underline' : undefined,
        color: run.color,
        fontSize: run.fontSize,
      })),
    }
  }
  return {
    stack: [
      ...(block.heading
        ? [
            {
              text: block.heading,
              bold: true,
              color: block.headingColor ?? primary,
              fontSize: block.headingFontSize ?? 8,
              margin: [0, 0, 0, 4],
            },
          ]
        : []),
      block.ordered ? { ol: items.map(renderItem) } : { ul: items.map(renderItem) },
    ],
  } as unknown as Content
}

function renderColumns(block: ReportColumns, primary: string): Content {
  return {
    columnGap: block.gap ?? 12,
    columns: block.columns.map((column) => ({
      width: column.width ?? '*',
      stack: column.blocks.map((child) => renderBlock(child, primary)),
    })),
  }
}

function renderSection(block: ReportSection, primary: string): Content {
  const accent = block.accent ?? primary
  return {
    unbreakable: block.keepTogether,
    margin: [0, 8, 0, 6],
    table: {
      widths: [4, '*'],
      body: [
        [
          { text: '', fillColor: accent, rowSpan: 2 },
          {
            stack: [
              { text: block.heading, bold: true, fontSize: 11, color: accent },
              ...(block.subheading
                ? [{ text: block.subheading, color: '#666666', fontSize: 8, margin: [0, 2, 0, 7] }]
                : []),
              ...block.blocks.map((child) => renderBlock(child, primary)),
            ],
            margin: [9, 7, 7, 7],
          },
        ],
        [{ text: '' }, { text: '' }],
      ],
    },
    layout: 'noBorders',
  } as unknown as Content
}
