import type { Content, TDocumentDefinitions } from 'pdfmake/interfaces'
import type {
  DocumentReport,
  ReportBlock,
  ReportColumns,
  ReportList,
  ReportParagraph,
  ReportSection,
  ReportTable,
} from '../types'

export async function renderPdf(report: DocumentReport): Promise<Uint8Array> {
  const [pdfMakeModule, vfsModule] = await Promise.all([
    import('pdfmake/build/pdfmake'),
    import('pdfmake/build/vfs_fonts'),
  ])
  const pdfMake = pdfMakeModule.default
  pdfMake.addVirtualFileSystem(vfsModule.default)

  const definition: TDocumentDefinitions = {
    info: {
      title: report.title,
      subject: report.subject,
      author: report.branding.churchName,
      creator: 'Worship Studio',
    },
    pageSize: 'LETTER',
    pageOrientation: report.orientation ?? 'portrait',
    pageMargins: report.showHeaderFooter === false ? [54, 54, 54, 54] : [54, 68, 54, 58],
    ...(report.showHeaderFooter === false
      ? {}
      : {
          header: {
            margin: [54, 24, 54, 0],
            columns: [
              {
                text: report.branding.churchName,
                color: report.branding.primaryColor,
                bold: true,
                fontSize: 9,
              },
              { text: report.title, alignment: 'right', color: '#777777', fontSize: 8 },
            ],
          },
          footer: (currentPage: number, pageCount: number) => ({
            margin: [54, 0, 54, 18],
            columns: [
              { text: 'Generated by Worship Studio', color: '#888888', fontSize: 7 },
              {
                text: `${currentPage} / ${pageCount}`,
                alignment: 'right',
                color: '#888888',
                fontSize: 7,
              },
            ],
          }),
        }),
    content: [
      ...(report.showTitle === false
        ? []
        : [{ text: report.title, style: 'reportTitle' } as Content]),
      ...(report.showTitle !== false && report.subtitle
        ? [{ text: report.subtitle, style: 'reportSubtitle' } as Content]
        : []),
      ...report.blocks.map((block) => renderBlock(block, report.branding.primaryColor)),
    ],
    defaultStyle: { font: 'Roboto', fontSize: 9, color: '#252A31', lineHeight: 1.2 },
    styles: {
      reportTitle: {
        fontSize: 20,
        bold: true,
        alignment: 'center',
        color: '#202833',
        margin: [0, 0, 0, 4],
      },
      reportSubtitle: { fontSize: 9, alignment: 'center', color: '#666666', margin: [0, 0, 0, 20] },
      heading: { fontSize: 12, bold: true, color: '#202833' },
      note: { fontSize: 8, italics: true, color: '#777777' },
    },
  }

  const buffer = await pdfMake.createPdf(definition).getBuffer()
  return new Uint8Array(buffer)
}

function renderBlock(block: ReportBlock, primary: string): Content {
  switch (block.kind) {
    case 'paragraph':
      return renderParagraph(block)
    case 'table':
      return renderTable(block, primary)
    case 'list':
      return renderList(block, primary)
    case 'columns':
      return renderColumns(block, primary)
    case 'section':
      return renderSection(block, primary)
  }
}

function renderParagraph(block: ReportParagraph): Content {
  return {
    text: block.runs.map((run) => ({
      text: run.text,
      bold: run.bold,
      italics: run.italics,
      color: run.color,
    })),
    alignment: block.alignment,
    style:
      block.style === 'title'
        ? 'reportTitle'
        : block.style === 'subtitle'
          ? 'reportSubtitle'
          : block.style === 'heading'
            ? 'heading'
            : block.style === 'note'
              ? 'note'
              : undefined,
    margin: [
      0,
      block.spacingBefore ?? 0,
      0,
      block.spacingAfter ?? (block.style === 'body' ? 2 : 5),
    ],
  } as unknown as Content
}

function renderTable(block: ReportTable, primary: string): Content {
  const header = block.headers.map((text) => ({
    text,
    bold: true,
    color: '#FFFFFF',
    fillColor: primary,
    fontSize: 8,
    margin: [2, 3, 2, 3],
  }))
  const rows = block.rows.map((row) =>
    row.map((cell) => ({
      text: cell.runs.map((run) => ({
        text: run.text,
        bold: run.bold,
        italics: run.italics,
        color: run.color,
      })),
      alignment: cell.alignment,
      margin: [2, 3, 2, 3],
      fontSize: 8,
    })),
  )
  return {
    table: {
      headerRows: block.headers.length ? (block.headerRows ?? 1) : 0,
      widths: block.widths ?? block.headers.map(() => '*'),
      body: block.headers.length ? [header, ...rows] : rows,
    },
    layout: {
      hLineColor: () => '#D9DDE3',
      vLineColor: () => '#D9DDE3',
      hLineWidth: () => 0.5,
      vLineWidth: () => 0.5,
    },
    margin: [0, 0, 0, 10],
  } as unknown as Content
}

function renderList(block: ReportList, primary: string): Content {
  const items = block.items.length ? block.items : [block.emptyText ?? 'None']
  return {
    stack: [
      ...(block.heading
        ? [{ text: block.heading, bold: true, color: primary, fontSize: 8, margin: [0, 0, 0, 4] }]
        : []),
      block.ordered
        ? {
            ol: items.map((text) => ({
              text,
              color: block.items.length ? undefined : '#777777',
              italics: !block.items.length,
            })),
          }
        : {
            ul: items.map((text) => ({
              text,
              color: block.items.length ? undefined : '#777777',
              italics: !block.items.length,
            })),
          },
    ],
  } as unknown as Content
}

function renderColumns(block: ReportColumns, primary: string): Content {
  return {
    columnGap: block.gap ?? 12,
    columns: block.columns.map((column) => ({
      width: column.width ?? '*',
      stack: column.blocks.map((child) => renderBlock(child, primary)),
    })),
  }
}

function renderSection(block: ReportSection, primary: string): Content {
  const accent = block.accent ?? primary
  return {
    unbreakable: block.keepTogether,
    margin: [0, 8, 0, 6],
    table: {
      widths: [4, '*'],
      body: [
        [
          { text: '', fillColor: accent, rowSpan: 2 },
          {
            stack: [
              { text: block.heading, bold: true, fontSize: 11, color: accent },
              ...(block.subheading
                ? [{ text: block.subheading, color: '#666666', fontSize: 8, margin: [0, 2, 0, 7] }]
                : []),
              ...block.blocks.map((child) => renderBlock(child, primary)),
            ],
            margin: [9, 7, 7, 7],
          },
        ],
        [{ text: '' }, { text: '' }],
      ],
    },
    layout: 'noBorders',
  } as unknown as Content
}
