<script setup lang="ts">
/**
 * Root component mounted by main.ts instead of App.vue directly. App.vue calls getAdapter()
 * synchronously at <script setup> module scope, so the adapter must already be resolved before
 * App.vue is even instantiated — this component exists to do that resolution first, showing a
 * chooser/resume UI only when it's actually needed, and rendering the real App.vue unchanged
 * once ready.
 *
 * Tauri resolves instantly, no UI shown. Every other web deploy — including the public GitHub
 * Pages build, deliberately not special-cased — shows the real "Open Your Library Folder" / "Try
 * the Demo" chooser, since a real usable web build hosted for free on Pages was the actual point,
 * not a fake pitch deck. The one exception: a `?demo=1` URL param skips straight to the mock
 * adapter with no chooser at all, for the docs landing page's dedicated "Try the Web Demo" link
 * (docs/index.md) to keep that a true one-click experience.
 *
 * Two "Connect Dropbox"/"Connect OneDrive" chooser options build the tablet (PWA) adapter instead
 * — for platforms (any tablet browser) where showDirectoryPicker() doesn't exist at all, syncing
 * directly against a cloud provider's API rather than a real picked folder (see adapters/tablet/,
 * whose CloudSyncProvider abstraction is what lets this file treat both providers identically
 * below via authFor()). This is also where the OAuth redirect lands on its way back for either
 * provider (a full top-level redirect, not a popup — see beginCloudConnect's own comment for
 * why), handled before anything else in onMounted so it takes priority over every other
 * resolution path — and where a `?connect=` link/QR code generated by another already-connected
 * device's Settings page (LibrarySyncSection.vue's "Add Another Device") lands too, pre-filling
 * and immediately starting the connect flow so a second device never needs its app key/client ID
 * typed in by hand.
 */
import { onMounted, ref } from 'vue'
import App from '@/App.vue'
import { getAdapter, isTauri, setAdapterInstance } from '@/adapters'
import { createMockAdapter } from '@/adapters/mock'
import { createWebAdapter } from '@/adapters/web'
import {
  clearStoredLibraryHandle,
  loadStoredLibraryHandle,
  storeLibraryHandle,
} from '@/adapters/web/handlePersistence'
import { createTabletAdapter } from '@/adapters/tablet'
import * as dropbox from '@/adapters/tablet/providers/dropboxAuth'
import * as onedrive from '@/adapters/tablet/providers/onedriveAuth'
import { getOpfsRoot } from '@/adapters/tablet/opfs'
import { createWebSettingsPort } from '@/adapters/web/settings'
import logoDark from '@/assets/logo-dark.png'

export type CloudProviderId = 'dropbox' | 'onedrive'

type Phase = 'resolving' | 'chooser' | 'resuming' | 'cloud-connect' | 'connecting-cloud' | 'ready'

const phase = ref<Phase>('resolving')
const errorText = ref('')
const pendingHandle = ref<FileSystemDirectoryHandle>()
const fsaSupported = typeof window !== 'undefined' && 'showDirectoryPicker' in window

const connectProvider = ref<CloudProviderId>('dropbox')
const cloudClientIdInput = ref('')
const cloudLibraryFolderPathInput = ref('')
const connectingCloud = ref(false)

// Survives the full top-level redirect to the provider and back (a popup would be unreliable on
// mobile Safari and in installed PWAs, so this can't just be a component-local variable —
// BootGate.vue itself gets fully re-mounted on the way back).
const CLOUD_OAUTH_PENDING_KEY = 'worship-studio:cloud-oauth-pending'

interface PendingCloudAuth {
  codeVerifier: string
  state: string
  provider: CloudProviderId
  clientId: string
  libraryFolderPath: string
  redirectUri: string
}

/** Both provider auth modules export identically-named functions with slightly different
 *  parameter shapes (Dropbox's `appKey` vs. OneDrive's `clientId`) — this adapts each to one
 *  shared shape so every call site below (the connect form, the OAuth-redirect handler, the
 *  already-connected reload check) can stay provider-agnostic, the same way adapters/tablet/'s
 *  own CloudSyncProvider interface does for the sync engine itself. */
interface CloudAuth {
  generateCodeVerifier: () => string
  codeChallengeFromVerifier: (verifier: string) => Promise<string>
  generateState: () => string
  buildAuthorizeUrl: (p: {
    clientId: string
    redirectUri: string
    state: string
    codeChallenge: string
  }) => string
  exchangeCodeForTokens: (p: {
    clientId: string
    redirectUri: string
    code: string
    codeVerifier: string
  }) => Promise<unknown>
  isConnected: () => Promise<boolean>
}

const dropboxAuth: CloudAuth = {
  generateCodeVerifier: dropbox.generateCodeVerifier,
  codeChallengeFromVerifier: dropbox.codeChallengeFromVerifier,
  generateState: dropbox.generateState,
  buildAuthorizeUrl: ({ clientId, redirectUri, state, codeChallenge }) =>
    dropbox.buildAuthorizeUrl({ appKey: clientId, redirectUri, state, codeChallenge }),
  exchangeCodeForTokens: ({ clientId, redirectUri, code, codeVerifier }) =>
    dropbox.exchangeCodeForTokens({ appKey: clientId, redirectUri, code, codeVerifier }),
  isConnected: dropbox.isConnected,
}

const oneDriveAuth: CloudAuth = {
  generateCodeVerifier: onedrive.generateCodeVerifier,
  codeChallengeFromVerifier: onedrive.codeChallengeFromVerifier,
  generateState: onedrive.generateState,
  buildAuthorizeUrl: onedrive.buildAuthorizeUrl,
  exchangeCodeForTokens: onedrive.exchangeCodeForTokens,
  isConnected: onedrive.isConnected,
}

function authFor(provider: CloudProviderId): CloudAuth {
  return provider === 'onedrive' ? oneDriveAuth : dropboxAuth
}

/** Builds the tablet adapter, caches the provider/client ID/library path locally (MachineSettings
 *  — localStorage-backed, not OPFS, so this is instant and needs no cloud round trip) so a later
 *  reload on this device boots straight back in without asking again, then activates it. */
async function finishTabletBoot(
  provider: CloudProviderId,
  clientId: string,
  libraryFolderPath: string,
  tabletMediaMaxCachedFileSizeMb?: number,
) {
  const adapter = await createTabletAdapter({
    provider,
    clientId,
    libraryFolderPath,
    tabletMediaMaxCachedFileSizeMb,
  })
  const machineSettings = await adapter.settings.getMachineSettings()
  await adapter.settings.saveMachineSettings({
    ...machineSettings,
    tabletCloudProvider: provider,
    tabletCloudClientId: clientId,
    tabletCloudLibraryFolderPath: libraryFolderPath,
  })
  setAdapterInstance(adapter)
  phase.value = 'ready'
}

async function beginCloudConnect() {
  errorText.value = ''
  const clientId = cloudClientIdInput.value.trim()
  if (!clientId) {
    errorText.value =
      connectProvider.value === 'onedrive'
        ? 'Enter the Microsoft app client ID first.'
        : 'Enter the Dropbox app key first.'
    return
  }
  connectingCloud.value = true
  try {
    const auth = authFor(connectProvider.value)
    const codeVerifier = auth.generateCodeVerifier()
    const codeChallenge = await auth.codeChallengeFromVerifier(codeVerifier)
    const state = auth.generateState()
    // The redirect the provider sends the browser back to has to exactly match what's registered
    // in that provider's app console — computed from the current origin/path rather than
    // hardcoded so this works unchanged across local dev and every real deployment.
    const redirectUri = `${window.location.origin}${window.location.pathname}`
    const libraryFolderPath = cloudLibraryFolderPathInput.value.trim()
    const pending: PendingCloudAuth = {
      codeVerifier,
      state,
      provider: connectProvider.value,
      clientId,
      libraryFolderPath,
      redirectUri,
    }
    sessionStorage.setItem(CLOUD_OAUTH_PENDING_KEY, JSON.stringify(pending))
    window.location.assign(auth.buildAuthorizeUrl({ clientId, redirectUri, state, codeChallenge }))
  } catch (error) {
    connectingCloud.value = false
    errorText.value = error instanceof Error ? error.message : "Couldn't start connecting."
  }
}

async function handleCloudRedirect(params: URLSearchParams) {
  phase.value = 'connecting-cloud'
  const code = params.get('code') ?? ''
  const state = params.get('state') ?? ''
  // Clean the URL immediately regardless of outcome, so refreshing this page never re-processes
  // (and re-fails, since these codes are single-use) the same code.
  window.history.replaceState({}, '', window.location.pathname)

  const pendingRaw = sessionStorage.getItem(CLOUD_OAUTH_PENDING_KEY)
  sessionStorage.removeItem(CLOUD_OAUTH_PENDING_KEY)
  const pending = pendingRaw ? (JSON.parse(pendingRaw) as PendingCloudAuth) : undefined
  if (!pending) {
    errorText.value =
      'The sign-in session expired, or was opened in a different tab. Please try connecting again.'
    phase.value = 'chooser'
    return
  }
  if (pending.state !== state) {
    errorText.value = "The sign-in response couldn't be verified. Please try again."
    phase.value = 'chooser'
    return
  }

  try {
    await authFor(pending.provider).exchangeCodeForTokens({
      clientId: pending.clientId,
      redirectUri: pending.redirectUri,
      code,
      codeVerifier: pending.codeVerifier,
    })
    await finishTabletBoot(pending.provider, pending.clientId, pending.libraryFolderPath)
  } catch (error) {
    errorText.value = error instanceof Error ? error.message : "Couldn't finish connecting."
    phase.value = 'chooser'
  }
}

onMounted(async () => {
  const params = new URLSearchParams(window.location.search)
  if (params.has('code') && params.has('state')) {
    await handleCloudRedirect(params)
    return
  }

  // A link/QR code from another already-connected device's Settings page ("Add Another Device")
  // — pre-fills and immediately starts the connect flow so this device never needs the app
  // key/client ID typed in by hand. The value isn't secret (see LibrarySyncSection.vue's own
  // comment on this), so carrying it in a URL is the same reasoning Remote Control's own pairing
  // link/QR already relies on.
  if (params.has('connect')) {
    window.history.replaceState({}, '', window.location.pathname)
    connectProvider.value = params.get('connect') === 'onedrive' ? 'onedrive' : 'dropbox'
    cloudClientIdInput.value = params.get('key') ?? ''
    cloudLibraryFolderPathInput.value = params.get('path') ?? ''
    phase.value = 'cloud-connect'
    if (cloudClientIdInput.value) await beginCloudConnect()
    return
  }

  if (isTauri()) {
    // Unchanged existing behavior — getAdapter() itself still knows how to resolve this, this
    // just makes sure it happens before App.vue reads it.
    setAdapterInstance(getAdapter())
    phase.value = 'ready'
    return
  }

  if (params.has('demo')) {
    setAdapterInstance(createMockAdapter())
    phase.value = 'ready'
    return
  }

  const stored = await loadStoredLibraryHandle().catch(() => undefined)
  if (stored) {
    const granted = await stored.queryPermission({ mode: 'readwrite' }).catch(() => 'prompt')
    if (granted === 'granted') {
      setAdapterInstance(createWebAdapter(stored))
      phase.value = 'ready'
      return
    }
    pendingHandle.value = stored
    phase.value = 'resuming'
    return
  }

  // A tablet that's already connected, returning on an ordinary reload (not an OAuth redirect
  // this time) — boot straight back in rather than showing the chooser again.
  const opfsRoot = await getOpfsRoot().catch(() => undefined)
  const cachedMachineSettings = await (opfsRoot
    ? createWebSettingsPort(opfsRoot).getMachineSettings()
    : undefined)
  const cachedProvider = cachedMachineSettings?.tabletCloudProvider
  const cachedClientId = cachedMachineSettings?.tabletCloudClientId
  if (cachedProvider && cachedClientId) {
    const alreadyConnected = await authFor(cachedProvider)
      .isConnected()
      .catch(() => false)
    if (alreadyConnected) {
      await finishTabletBoot(
        cachedProvider,
        cachedClientId,
        cachedMachineSettings?.tabletCloudLibraryFolderPath ?? '',
        cachedMachineSettings?.tabletMediaMaxCachedFileSizeMb,
      )
      return
    }
  }

  phase.value = 'chooser'
})

async function chooseDemo() {
  setAdapterInstance(createMockAdapter())
  phase.value = 'ready'
}

async function chooseFolder() {
  errorText.value = ''
  try {
    const handle = await window.showDirectoryPicker({ mode: 'readwrite' })
    await storeLibraryHandle(handle)
    setAdapterInstance(createWebAdapter(handle))
    phase.value = 'ready'
  } catch (error) {
    // AbortError: the user cancelled the native picker — not a real failure, just stay put.
    if ((error as DOMException)?.name !== 'AbortError') {
      errorText.value = 'Could not open that folder. Please try again.'
    }
  }
}

async function resumeAccess() {
  errorText.value = ''
  const handle = pendingHandle.value
  if (!handle) return
  const granted = await handle.requestPermission({ mode: 'readwrite' }).catch(() => 'denied')
  if (granted === 'granted') {
    setAdapterInstance(createWebAdapter(handle))
    phase.value = 'ready'
    return
  }
  errorText.value = 'Access was not granted. You can pick a folder again below.'
}

async function pickDifferentFolder() {
  await clearStoredLibraryHandle().catch(() => {})
  pendingHandle.value = undefined
  errorText.value = ''
  phase.value = 'chooser'
}

function showCloudConnectForm(provider: CloudProviderId) {
  errorText.value = ''
  connectProvider.value = provider
  phase.value = 'cloud-connect'
}
</script>

<template>
  <App v-if="phase === 'ready'" />
  <div v-else class="boot-gate">
    <v-card class="boot-card" elevation="8">
      <v-card-text class="boot-card-content">
        <img :src="logoDark" alt="Worship Studio" class="boot-logo" />

        <template v-if="phase === 'resolving'">
          <p class="boot-status">Loading…</p>
        </template>

        <template v-else-if="phase === 'chooser'">
          <p class="boot-lead">
            Open your church's library folder to prepare services, or try the demo with sample data.
          </p>
          <v-btn color="primary" size="large" block :disabled="!fsaSupported" @click="chooseFolder">
            Open Your Library Folder
          </v-btn>
          <p v-if="!fsaSupported" class="boot-note">
            This browser doesn't support opening a real folder — try Chrome or Edge. You can still
            try the demo below.
          </p>
          <v-btn
            variant="outlined"
            size="large"
            block
            class="mt-2"
            @click="showCloudConnectForm('dropbox')"
          >
            Connect Dropbox
          </v-btn>
          <v-btn
            variant="outlined"
            size="large"
            block
            class="mt-2"
            @click="showCloudConnectForm('onedrive')"
          >
            Connect OneDrive
          </v-btn>
          <p class="boot-note">
            For tablets and phones, where opening a real folder isn't possible — syncs directly
            with your church's Dropbox or OneDrive instead. If another device is already
            connected, use its Settings page to scan a link instead of typing anything below.
          </p>
          <v-btn variant="text" size="large" block class="mt-2" @click="chooseDemo">
            Try the Demo
          </v-btn>
        </template>

        <template v-else-if="phase === 'resuming'">
          <p class="boot-lead">Resume access to your library folder to continue.</p>
          <v-btn color="primary" size="large" block @click="resumeAccess">Resume Access</v-btn>
          <v-btn variant="text" size="large" block class="mt-2" @click="pickDifferentFolder">
            Pick a Different Folder
          </v-btn>
        </template>

        <template v-else-if="phase === 'cloud-connect'">
          <p class="boot-lead">
            Connect to your church's {{ connectProvider === 'onedrive' ? 'OneDrive' : 'Dropbox' }}
            account to sync this device's library.
          </p>
          <v-text-field
            v-model="cloudClientIdInput"
            :label="connectProvider === 'onedrive' ? 'Microsoft app client ID' : 'Dropbox app key'"
            variant="outlined"
            density="comfortable"
            autocomplete="off"
            hint="Needed once per church, not once per device — ask whoever registered the app, or (on any device that's already connected) go to Settings and use Add Another Device to skip typing this in."
            persistent-hint
            class="mb-3"
          />
          <v-text-field
            v-model="cloudLibraryFolderPathInput"
            label="Library folder path (optional)"
            variant="outlined"
            density="comfortable"
            autocomplete="off"
            placeholder="/Church/WorshipStudio Library"
            hint="Leave blank if the library lives at the root of the account."
            persistent-hint
            class="mb-3"
          />
          <v-btn
            color="primary"
            size="large"
            block
            :loading="connectingCloud"
            @click="beginCloudConnect"
          >
            Connect {{ connectProvider === 'onedrive' ? 'OneDrive' : 'Dropbox' }}
          </v-btn>
          <v-btn variant="text" size="large" block class="mt-2" @click="phase = 'chooser'">
            Back
          </v-btn>
        </template>

        <template v-else-if="phase === 'connecting-cloud'">
          <p class="boot-status">Finishing sign-in…</p>
        </template>

        <p v-if="errorText" class="boot-error" role="alert">{{ errorText }}</p>
      </v-card-text>
    </v-card>
  </div>
</template>

<style scoped>
.boot-gate {
  position: fixed;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 16px;
}
.boot-card {
  width: 100%;
  max-width: 420px;
}
.boot-card-content {
  display: flex;
  flex-direction: column;
  align-items: stretch;
  gap: 12px;
  padding: 32px 28px;
  text-align: center;
}
.boot-logo {
  align-self: center;
  width: min(70%, 260px);
  height: auto;
  margin-bottom: 8px;
}
.boot-lead {
  margin-bottom: 8px;
  opacity: 0.85;
}
.boot-status {
  opacity: 0.7;
}
.boot-note {
  margin-top: -4px;
  font-size: 0.8rem;
  opacity: 0.65;
}
.boot-error {
  margin-top: 4px;
  color: rgb(var(--v-theme-error));
  font-size: 0.85rem;
}
</style>
